project:
  type: website
  output-dir: docs

website:
  title: "PHCM9795"
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - software.qmd
      - q_and_a.qmd
#      - course-intro.qmd
#      - download-mac.qmd
#      - download-win.qmd
#      - download-videos.qmd
#      - cheatsheet-jamovi.qmd
#      - cheatsheet-R.qmd
  google-analytics: "G-VQHR7ETRKE"

format:
  html:
    theme: cosmo
    highlight-style: monochrome
    title-block-banner: "#ffdc00"
    link-external-icon: true
    link-external-newwindow: true
